### ISSUE TITLE
Docker hub users for deploying

### ISSUE THREAD

**Issue by Beanow** [sourcecred/sourcecred#1334]
For https://github.com/sourcecred/sourcecred/pull/1320 and https://github.com/sourcecred/widgets/pull/22 I've created Docker Hub users to use for automatic deployments. Aside from sharing the credentials (#1333) I wanted to discuss and document the setup and rationale in more detail.

### The problem

Docker Hub provides neither 2FA nor deploy keys to limit the privileges of credentials. Meaning, you're expected to insert the username and password of your user account to push built images to Docker Hub. For CI environments this is way too many privileges.

The only alternative I know of for Docker Hub is to switch to their build platform.
https://docs.docker.com/docker-hub/builds/

Which moves the problem from username/passwords to Github access tokens having access to way too many repositories. And suffered a recent breach as well: https://success.docker.com/article/docker-hub-user-notification

### The workaround

Creating users as if they are deploy keys, granting the minimum required access to one Docker Hub repository only.

Some major drawbacks of this approach over having actual deploy key support I can think of are, these credentials will be valid for operations such as managing the account settings of the deploy user, and they have additional attack vectors because they are users (such as password resetting over email).

Because of this, I think if we ever suspect a deploy user is compromised, _it's access should be revoked, the user abandoned entirely and replaced with a new one._ As if you were rotating a key.

#### Teams

On Docker Hub, you can't grant individual users permissions for a repo.
So we need a team for each repo, it looks a bit like this.

```yml
sourcecred-org:
  repos:
    - sourcecred
    - widgets
  teams:
    # Real developer accounts with admin privileges
    owners:
      - decentralion
      - beanow
    # Read-write for sourcecred/sourcecred deployments
    deploysourcecred:
      - (some deploy user)
    # Read-write for sourcecred/widgets deployments
    deploywidgets:
      - (some deploy user)
```

#### Usernames

As I mentioned previously, in case of a compromised deploy user, I think we should rotate to a new user entirely. With that in mind I formatted usernames as
`scdeploy | <repository> | <date YYYYMM> | <random>`
so for example `scdeploywidgets201908lae5gol2` for sourcecred/widgets.
It includes their usage and avoids conflicts.

_(Would have improved this but usernames are limited to lowercase alphanumerical and max 32 characters.)_

#### Passwords

Since the password will be passed around through several environments such as ENV vars, templating steps and CLI commands, I think special characters should be avoided here. Instead using longer random passwords.

### Really?

I'm afraid so :worried:

But there is a final option we can turn to. Alternative registries.
Services like [Quay.io](https://quay.io/) and [GitHub Package Registry](https://github.com/features/package-registry) can be used instead of Docker Hub.

The drawback is in discovery and having longer image names.
For example on GitHub Package Registry the sourcecred image would go from
`sourcecred/sourcecred` to `docker.pkg.github.com/sourcecred/sourcecred`
Although quay isn't as bad. `quay.io/sourcecred/sourcecred`

Developers who've made a habit of using a Docker Hub search to find images (I know I have)
https://hub.docker.com/search/?q=sourcecred&type=image
would not find sourcecred here should we move.

If this provide significantly better security moving forward, it may be worth looking into them.
